---
###
###
###
###
### this is based on the restrictive scc, but removes allowPrivilegeEscalation as this is not required?
###

kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: application-platform-general-scc

###
### values needed for the security context of the kapp-controller
###

runAsUser:
  type: MustRunAsRange
  uidRangeMin: 65532
  uidRangeMax: 65534

###
### required values in a security context controller
###
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
seLinuxContext:
  type: MustRunAs

###
### make sure this is only used by the secretgen-controller-sa
###
users:
  - system:serviceaccount:tanzu-system-ingress:contour
---
###
### role for binding serviceaccount to constraint
###
### reference for binding serviceaccount to constraint
### https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html#role-based-access-to-ssc_configuring-internal-oauth
###
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-platform-general-cluster-role
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - application-platform-general-scc
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
###
### role binding for binding serviceaccount to constraint
###
apiVersion: rbac.authorization.k8s.io/v1
# This role binding grants "secretgen-controller-sa" membership to Role cluster-essentials-secretgen-controller-role
kind: ClusterRoleBinding
metadata:
  name: application-platform-general-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: application-platform-general-cluster-role
subjects:
  - kind: ServiceAccount
    namespace: tanzu-system-ingress
    name: contour
