---
###
### security context constraints required to install the carvel kapp-controller
### * required until version v0.9.1 of carvel kapp controller is released
###
### this is based on the restrictive scc, but removes allowPrivilegeEscalation as this is not required?
###

kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: cluster-essentials-kapp-controller

###
### values needed for the security context of the kapp-controller
###

allowPrivilegeEscalation: false
#capabilities:
#  drop:
#   - all
readOnlyRootFilesystem: false
#runAsNonRoot: true

###
### required values in a security context controller
###
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
seLinuxContext:
  type: MustRunAs
runAsUser:
  type: MustRunAsRange

###
### make sure this is only used by the secretgen-controller-sa
###
users:
  - system:serviceaccount:kapp-controller:kapp-controller-sa
---
###
### role for binding serviceaccount to constraint
###
### reference for binding serviceaccount to constraint
### https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html#role-based-access-to-ssc_configuring-internal-oauth
###
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-essentials-kapp-controller-role
  namespace: kapp-controller
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - cluster-essentials-kapp-controller
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
###
### role binding for binding serviceaccount to constraint
###
apiVersion: rbac.authorization.k8s.io/v1
# This role binding grants "secretgen-controller-sa" membership to Role cluster-essentials-secretgen-controller-role
kind: RoleBinding
metadata:
  name: cluster-essentials-kapp-controller-role-binding
  namespace: kapp-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-essentials-kapp-controller-role
subjects:
  - kind: ServiceAccount
    name: kapp-controller-sa
    namespace: kapp-controller