---
###
### security context constraints required to install the secretgen-controller
### * required until version v0.9.1 of carvel secretgen controller is released
###
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: cluster-essentials-secretgen-controller

###
### values needed for the security context of the secretgen-controller
###

runAsUser:
  type: MustRunAs
  uid: 1000
fsGroup:
  type: RunAsAny

###
### required values in a security context controller
###
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
seLinuxContext:
  type: MustRunAs

###
### make sure this is only used by the secretgen-controller-sa
###
users:
  - system:serviceaccount:secretgen-controller:secretgen-controller-sa
---
###
### role for binding serviceaccount to constraint
###
### reference for binding serviceaccount to constraint
### https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html#role-based-access-to-ssc_configuring-internal-oauth
###
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-essentials-secretgen-controller-role
  namespace: secretgen-controller
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - cluster-essentials-secretgen-controller
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
###
### role binding for binding serviceaccount to constraint
###
apiVersion: rbac.authorization.k8s.io/v1
# This role binding grants "secretgen-controller-sa" membership to Role cluster-essentials-secretgen-controller-role
kind: RoleBinding
metadata:
  name: cluster-essentials-secretgen-controller-role-binding
  namespace: secretgen-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-essentials-secretgen-controller-role
subjects:
  - kind: ServiceAccount
    name: secretgen-controller-sa
    namespace: secretgen-controller