---
###
### security context constraints required to install the tap-gui
###
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: tap-gui-scc

###
### values needed for the security context of the tap-gui-scc
###

runAsUser:
  type: MustRunAs
  uid: 1000
fsGroup:
  type: RunAsAny

###
### required values in a security context 
###
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
seLinuxContext:
  type: MustRunAs

###
### make sure this is only used by the default service account in the tap-gui namespace
###
users:
  - system:serviceaccount:tap-gui:default
---
###
### role for binding serviceaccount to constraint
###
### reference for binding serviceaccount to constraint
### https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html#role-based-access-to-ssc_configuring-internal-oauth
###
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tap-gui-scc-cluster-role
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - tap-gui-scc
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
###
### role binding for binding serviceaccount to constraint
###
apiVersion: rbac.authorization.k8s.io/v1
# This role binding grants the "default" service accounts in the tap-gui namespace membership to Role tap-gui-scc-role
kind: ClusterRoleBinding
metadata:
  name: tap-gui-scc-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tap-gui-scc-cluster-role
subjects:
  - kind: ServiceAccount
    namespace: tap-gui
    name: default