#@ load("@ytt:data", "data")
---
profile: full
ceip_policy_disclosed: true # Installation fails if this is set to 'false'
buildservice:
  kp_default_repository: #@ "{}/{}/build-service".format(data.values.container_registry.hostname,data.values.container_registry.project)
  kp_default_repository_username: #@ data.values.container_registry.username
  kp_default_repository_password: #@ data.values.container_registry.password
  tanzunet_username: #@ data.values.tanzunet.username
  tanzunet_password: #@ data.values.tanzunet.password
  enable_automatic_dependency_updates: true
  descriptor_name: full

supply_chain: testing_scanning

ootb_supply_chain_testing_scanning:
  registry:
    server: #@ data.values.container_registry.hostname
    repository: #@ data.values.container_registry.project_workload
  gitops:
    ssh_secret: ""

learningcenter:
  ingressDomain: #@ "learning-center.{}".format(data.values.ingress.domain)
  ingressSecret:
    secretName: #@ "learning-center-{}".format(data.values.ingress.contour_tls_secret)

tap_gui:
  ingressEnabled: true
  ingressDomain: #@ data.values.ingress.domain
  service_type: ClusterIP # NodePort for distributions that don't support LoadBalancer
  tls:
    secretName: #@ data.values.ingress.contour_tls_secret
    namespace: #@ data.values.ingress.contour_tls_namespace
  app_config:
    backend:
      baseUrl: #@ "https://tap-gui.{}".format(data.values.ingress.domain)
      cors:
        origin: #@ "https://tap-gui.{}".format(data.values.ingress.domain)
    app:
      baseUrl: #@ "https://tap-gui.{}".format(data.values.ingress.domain)
    integrations:
      github:
        - host: #@ data.values.gitrepo.host
          token: #@ data.values.gitrepo.token
    catalog:
      locations:
        - type: url
          target: #@ data.values.catalog.location
#    auth:
#      environment: #@ data.values.tap.auth.oauthApp
#      providers:
#        github:
#          #@: data.values.tap.auth.oauthApp
#            clientId: #@ data.values.tap.auth.client_id
#            clientSecret: #@ data.values.tap.auth.client_secret

metadata_store:
  app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

contour:
  envoy:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: #@ "*.{}".format(data.values.ingress.domain)
      type: LoadBalancer

accelerator: 
  domain: #@ "{}".format(data.values.ingress.domain)                         
  ingress:
    include: true
  tls:
    secretName: #@ data.values.ingress.contour_tls_secret
    namespace: #@ data.values.ingress.contour_tls_namespace
  server:
    service_type: ClusterIP

cnrs:
  domain_name: #@ "cnr.{}".format(data.values.ingress.domain)
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  default_tls_secret: #@ "{}/cnr-{}".format(data.values.ingress.contour_tls_namespace,data.values.ingress.contour_tls_secret)

grype:
  namespace: #@ data.values.developer_namespace
  targetImagePullSecret: registry-credentials

#excluded_packages:
#  - ootb-supply-chain-basic.tanzu.vmware.com
#  - scanning.apps.tanzu.vmware.com
#  - grype.scanning.apps.tanzu.vmware.com
#  - metadata.store.apps.tanzu.vmware.com
