#@data/values
---
tanzunet:
  username: user@example.com
  password:
ceip_policy_disclosed: true # Installation fails if this is set to 'false'
ingress:
  domain: example.com # In case you want to use a subdomain(e.g. tap.aws.example.com) of your configured hosted zone(e.g. aws.example.com), you have to change the "--domain-filter=" argument value for the external-dns Deployment in the ingress-config/external-dns.yaml to the hosted zone domain(e.g. aws.example.com) instead of the variable value (which is the subdomain)!
  contour_tls_namespace: tanzu-system-ingress
  contour_tls_secret: contour-tls-delegation-cert
  contour_tls_key_pair: contour-tls-delegation-key-pair
container_registry:
  hostname: harbor.example.com
  project: tap
  project_workload: tap-wkld
  username: admin
  password: 
developer_namespace: dev-space
acme:
  email: user@example.com
aws:
  region: eu-central-1
  credentials: # Note internal VMware users: CloudGate credentials will not have the necessary permissions to work
    accessKey: 
    secretKey: 
  route_fifty_three_zone_id:
gitrepo:
  host: github.com
  token: <github_token>
catalog:
  location: https://github.com/<CATALOG-INFO-REPO>/git-catalog/blob/main/catalog-info.yaml
tap:
  auth:
    oauthApp: <github.oauthapp.oauthAppName>
    client_id: <github.oauthapp.client_id>
    client_secret: <github.oauthapp.client_secret>
# see reference: https://cert-manager.io/next-docs/configuration/ca/#deployment
cert-manager:
  custom-ca:
    certificate: <cat crt.pem | base64 -w0>
    key: <cat crt.pem | base64 -b0>