---
###
### security context constraints required to install the learningcenter
###
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: learningcenter-scc

###
### values needed for the security context of the learningcenter-scc
###

runAsUser:
  type: MustRunAs
  uid: 1
fsGroup:
  type: RunAsAny

###
### required values in a security context 
###
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
seLinuxContext:
  type: MustRunAs

###
### make sure this is only used by the default service account in the learningcenter namespace
###
users:
  - system:serviceaccount:learningcenter:default
---
###
### role for binding serviceaccount to constraint
###
### reference for binding serviceaccount to constraint
### https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html#role-based-access-to-ssc_configuring-internal-oauth
###
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: learningcenter-scc-cluster-role
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - learningcenter-scc
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
###
### role binding for binding serviceaccount to constraint
###
apiVersion: rbac.authorization.k8s.io/v1
# This role binding grants the "default" service accounts in the learningcenter namespace membership to Role learningcenter-scc-role
kind: ClusterRoleBinding
metadata:
  name: learningcenter-scc-cluster-role-binding
  namespace: learningcenter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: learningcenter-scc-cluster-role
subjects:
  - kind: ServiceAccount
    namespace: learningcenter
    name: default