---
###
### security context constraints required to install the app-live-view-connector and app-live-view-conventions
#### this SCC is only to be used by the following service accounts
####  - system:serviceaccount:app-live-view-connector:app-live-view-connector-service-account
####  - system:serviceaccount:app-live-view-conventions:default
###
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: tap-scc-3

###
### values needed for the security context of the app-live-view-connector-scc
###
runAsUser:
  type: MustRunAs
  uid: 1000
fsGroup:
  type: RunAsAny

###
### required values in a security context 
###
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
seLinuxContext:
  type: MustRunAs

---
###
### role for binding serviceaccount to constraint
###
### reference for binding serviceaccount to constraint
### https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html#role-based-access-to-ssc_configuring-internal-oauth
###
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tap-scc-cluster-role-3
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - tap-scc-3
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
###
### role binding for binding serviceaccount to constraint
###
apiVersion: rbac.authorization.k8s.io/v1
# This role binding grants the "app-live-view-connector-service-account" service account in the app-live-view-connector namespace membership to Role app-live-view-connector-scc-role
# This role binding also grants the "default" service account in the app-live-view-conventions namespace membership to Role app-live-view-connector-scc-role
kind: ClusterRoleBinding
metadata:
  name: tap-scc-cluster-role-binding-3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tap-scc-cluster-role-3
subjects:
  - kind: ServiceAccount
    namespace: app-live-view-connector
    name: app-live-view-connector-service-account
  - kind: ServiceAccount
    namespace: app-live-view-conventions
    name: default