#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: #@ data.values.ingress.contour_tls_key_pair
  namespace: #@ data.values.ingress.contour_tls_namespace
spec:
  isCA: true
  commonName: #@ "*.{}".format(data.values.ingress.domain)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-contour-cluster-issuer
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: #@ data.values.ingress.contour_tls_key_pair
  renewBefore: 360h0m0s

