#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: #@ "cnr-{}".format(data.values.ingress.contour_tls_secret)
  namespace: #@ data.values.ingress.contour_tls_namespace
spec:
  isCA: false
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  commonName: #@ "*.cnr.{}".format(data.values.ingress.domain)
  dnsNames:
    - #@ "*.cnr.{}".format(data.values.ingress.domain)
  secretName: #@ "cnr-{}".format(data.values.ingress.contour_tls_secret)
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  subject:
    organizations:
      - vmware
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-contour-cluster-issuer
    group: cert-manager.io
