---
###
### security context constraints required to install the carvel kapp-controller
### * partly required until version v0.9.1 of carvel kapp controller is released
### * also required until the pull request include finalizers in the apiGroup Resource rules is released
###
### this is based on the restrictive scc, but removes allowPrivilegeEscalation as this is not required for the kapp controller
###
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: supply-chain-scc

###
### values needed for the security context of the kapp-controller
###
allowPrivilegeEscalation: false
runAsUser:
  type: RunAsAny
###
### required values in a security context controller
###
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
seLinuxContext:
  type: MustRunAs
runAsUser:
  type: MustRunAsRange

#from restricted scc
allowedCapabilities: null
priority: null
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret

---
###  this is a prototype role and role binding to attempt to remove the requirement that we run the following work arounds to deploy the test app in openshift
# kubectl create clusterrolebinding dev-space --clusterrole=cluster-admin --serviceaccount=dev-space:default
# kubectl delete clusterrolebinding dev-space
# latest role and rolebinding to get pat, but now i'm getting this error
#$ tanzu apps workload get tanzu-java-web-app -n dev-space
#  tanzu-java-web-app: Unknown
#---
#lastTransitionTime: "2022-05-28T14:42:41Z"
#message: waiting to read value [.status.outputs.url] from resource [runnable.carto.run/tanzu-java-web-app]
#  in namespace [dev-space]
#reason: MissingValueAtPath
#status: Unknown
#type: Ready
#
#  Pods
#  NAME                                STATUS   RESTARTS   AGE
#
# try to delete and re-create dev-space and apply these roles and role-binding before deploying fluxcd
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: supply-chain-role
  namespace: dev-space
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - supply-chain-scc
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - apiGroups:
      - fluxcd.io
    resources:
      - finalizers
    verbs:
      - '*'
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - gitrepositories
      - gitrepositories/finalizers
    verbs:
      - '*'
  - apiGroups:
      - scanning.apps.tanzu.vmware.com
    resources:
      - imagescans
      - imagescans/finalizers
      - sourcescans
      - sourcescans/finalizers
#? following from where
      - scanpolicies
      - scanpolicies/finalizers
      - scantemplates
      - scantemplates/finalizers
    verbs:
      - '*'
  - apiGroups:
      - source.apps.tanzu.vmware.com
    resources:
      - imagerepositories
      - imagerepositories/finalizers
    verbs:
      - '*'
  - apiGroups:
      - carto.run
    resources:
      - clusterconfigtemplates
      - clusterconfigtemplates/finalizers
      - clusterdeliveries
      - clusterdeliveries/finalizers
      - clusterdeploymenttemplates
      - clusterdeploymenttemplates/finalizers
      - clusterimagetemplates
      - clusterimagetemplates/finalizers
      - clusterruntemplates
      - clusterruntemplates/finalizers
      - clustersourcetemplates
      - clustersourcetemplates/finalizers
      - clustersupplychains
      - clustersupplychains/finalizers
      - clustertemplates
      - clustertemplates/finalizers
      - deliverables
      - deliverables/finalizers
      - runnables
      - runnables/finalizers
      - workloads
      - workloads/finalizers
    verbs:
      - '*'
  - apiGroups:
      - kpack.io
    resources:
      - images
      - images/finalizers
    verbs:
      - '*'
  - apiGroups:
      - conventions.apps.tanzu.vmware.com
    resources:
      - podintents
      - podintents/finalizers
    verbs:
      - '*'
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns
      - taskruns/finalizers
      - pipelineruns
      - pipelineruns/finalizers
      - pipelines
      - pipelines/finalizers
    verbs:
      - '*'
  - apiGroups:
      - kappctrl.k14s.io
    resources:
      - apps
      - apps/finalizers
    verbs:
      - '*'
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
      - services/finalizers
    verbs:
      - '*'
  - apiGroups:
      - servicebinding.io
    resources:
      - servicebindings
      - servicebindings/finalizers
    verbs:
      - '*'
  - apiGroups:
      - services.apps.tanzu.vmware.com
    resources:
      - resourceclaims
      - resourceclaims/finalizers
    verbs:
      - '*'
  ###
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: supply-chain-role-binding
  namespace: dev-space
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: supply-chain-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dev-space
  - kind: ServiceAccount
    name: builder
    namespace: dev-space
  - kind: ServiceAccount
    name: deployer
    namespace: dev-space


