apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: supply-chain-role
  namespace: dev-space
rules:
  - apiGroups: [security.openshift.io]
    resourceNames: [supply-chain-scc]
    resources: [securitycontextconstraints]
    verbs: [use]
  - apiGroups: [fluxcd.io]
    resources: [finalizers]
    verbs: ['*']
  - apiGroups: [source.toolkit.fluxcd.io]
    resources: [gitrepositories, gitrepositories/finalizers]
    verbs: ['*']
  - apiGroups: [source.apps.tanzu.vmware.com]
    resources: [imagerepositories, imagerepositories/finalizers]
    verbs: ['*']
  - apiGroups: [carto.run]
    resources: [deliverables, deliverables/finalizers, runnables, runnables/finalizers, workloads, workloads/finalizers]
    verbs: ['*']
  - apiGroups: [carto.run]
    resources: [clusterconfigtemplates, clusterconfigtemplates/finalizers, clusterdeliveries, clusterdeliveries/finalizers, clusterdeploymenttemplates, clusterdeploymenttemplates/finalizers, clusterimagetemplates, clusterimagetemplates/finalizers, clusterruntemplates, clusterruntemplates/finalizers, clustersourcetemplates, clustersourcetemplates/finalizers, clustersupplychains, clustersupplychains/finalizers, clustertemplates, clustertemplates/finalizers ]
    verbs: ['*']
  - apiGroups: [kpack.io]
    resources: [images, images/finalizers]
    verbs: ['*']
  - apiGroups: [conventions.apps.tanzu.vmware.com]
    resources: [podintents, podintents/finalizers]
    verbs: ['*']
  - apiGroups: [""]
    resources: ['configmaps']
    verbs: ['*']
  - apiGroups: [""]
    resources: ['pods']
    verbs: ['list']
  - apiGroups: [tekton.dev]
    resources: [taskruns, taskruns/finalizers, pipelineruns, pipelineruns/finalizers]
    verbs: [ '*' ]
  - apiGroups: [tekton.dev]
    resources: [ pipelines, pipelines/finalizers ]
    vergs: ['list']
  - apiGroups: [kappctrl.k14s.io]
    resources: [apps, apps/finalizers]
    verbs: [ '*' ]
  - apiGroups: [serving.knative.dev]
    resources: [services, services/finalizers]
    verbs: [ '*' ]
  - apiGroups: [servicebinding.io]
    resources: [servicebindings,servicebindings/finalizers]
    verbs: [ '*' ]
  - apiGroups: [services.apps.tanzu.vmware.com]
    resources: [resourceclaims, resourceclaims/finalizers]
    verbs: [ '*' ]
  - apiGroups: [scanning.apps.tanzu.vmware.com]
    #? scanpolicies and scantemplates from where
    resources: [imagescans, imagescans/finalizers, sourcescans, sourcescans/finalizers, scanpolicies, scanpolicies/finalizers, scantemplates, scantemplates/finalizers]
    verbs: [ '*' ]
