apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: supply-chain-role
rules:
  - apiGroups: [security.openshift.io]
    resourceNames: [supply-chain-scc]
    resources: [securitycontextconstraints]
    verbs: [use]
  - apiGroups: [fluxcd.io]
    resources: [finalizers]
    verbs: ['*']
  - apiGroups: [source.apps.tanzu.vmware.com]
    resources: [imagerepositories]
    verbs: ['*']
  - apiGroups: [carto.run]
    resources: [deliverables, runnables]
    verbs: ['*']
  - apiGroups: [kpack.io]
    resources: [images]
    verbs: ['*']
  - apiGroups: [conventions.apps.tanzu.vmware.com]
    resources: [podintents]
    verbs: ['*']
  - apiGroups: [""]
    resources: ['configmaps']
    verbs: ['*']
  - apiGroups: [""]
    resources: ['pods']
    verbs: ['list']
  - apiGroups: [tekton.dev]
    resources: [taskruns, pipelineruns]
    verbs: ['*']
  - apiGroups: [tekton.dev]
    resources: [pipelines]
    verbs: ['list']
  - apiGroups: [kappctrl.k14s.io]
    resources: [apps]
    verbs: ['*']
  - apiGroups: [serving.knative.dev]
    resources: ['services']
    verbs: ['*']
  - apiGroups: [servicebinding.io]
    resources: ['servicebindings']
    verbs: ['*']
  - apiGroups: [services.apps.tanzu.vmware.com]
    resources: ['resourceclaims']
    verbs: ['*']
  - apiGroups: [scanning.apps.tanzu.vmware.com]
    resources: ['imagescans', 'sourcescans']
    verbs: ['*']
